apiVersion: batch/v1
kind: Job
metadata:
  name: pre-sync-job
  annotations:
    argocd.argoproj.io/hook: PreSync
spec:
  template:
    spec:
      containers:
        - name: print-message
          image: busybox
          command: ["sh", "-c", "echo 'Pré-synchronisation ArgoCD'"]
      restartPolicy: Never
  backoffLimit: 0

